version: "2.2"

services:
  postgres:
    container_name: database
    image: postgres
    environment:
      POSRGRES_USER: ${POSRGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345}
    volumes:
      - ./Base:/docker-entrypoint-initdb.d
    expose:
      - 5432
    networks:
      - pokesql
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-some@email.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 127.0.0.1:${PGADMIN_PORT:-5050}:80
    networks:
      - pokesql
    restart: unless-stopped
  backend:
    container_name: back
    image: rust
    environment:
      DATABASE_URL: postgresql://postgres:12345@postgres/postgres?sslmode=prefer
    volumes:
      - ./Back:/back
    entrypoint: cargo run --release
    working_dir: /back
    restart: unless-stopped
    expose:
      - 8000
    networks:
      - frontend
      - pokesql
  frontend:
    container_name: front
    image: alexsuch/angular-cli
    volumes:
      - ./Front:/front
    entrypoint: ng serve --host 0.0.0.0
    working_dir: /front
    ports:
      - ${FRONTEND_PORT:-4200}:4200
    restart: unless-stopped
    networks:
      - pokesql
      - frontend

networks:
  pokesql:
    driver: bridge
  frontend:
    driver: bridge
