CALL addRegionArena('Kanto', 'Grass', 'kanto_gym');
CALL addRegionArena('Johto', 'Fire', 'johto_gym');
CALL addRegionArena('Hoenn', 'Ground', 'hoenn_arena');
CALL addRegionArena('Sinnoh', 'Water', 'sinnoh_gym');
CALL addRegionArena('Unova', 'Normal', 'unova_arena');
CALL addRegionArena('Kalos', 'Dragon', 'kalos_battlefield');
CALL addRegionArena('Alola', 'Flying', 'alola_gym');
CALL addRegionArena('Galar', 'Ice', 'galar_arena');
CALL addRegionArena('Paldea', 'Dark', 'paldea_colloseum');
